[package]
name = "canvas_traits"
version = "0.0.1"
authors = ["The Servo Project Developers"]
publish = false

[lib]
name = "canvas_traits"
path = "lib.rs"

[dependencies]
azure = {git = "https://github.com/servo/rust-azure", features = ["plugins"]}
cssparser = {version = "0.5.4", features = ["heap_size", "serde-serialization"]}
euclid = {version = "0.6.4", features = ["plugins"]}
gfx_traits = {path = "../gfx_traits"}
heapsize = "0.3.0"
heapsize_plugin = "0.1.2"
ipc-channel = {git = "https://github.com/servo/ipc-channel"}
plugins = {path = "../plugins"}
serde = {version = "0.7", features = [ "nightly" ]}
serde_macros = "0.7"
webrender_traits = {git = "https://github.com/servo/webrender_traits"}

